const searchConfig = {
  advanceRequest: [
    "arNumber",
    "department",
    "suggestedSupplier",
    "requestedBy",
    "address",
    "finalDeliveryPoint",
    "city",
    "accountNumber",
    "accountName",
    "bankName",
    "expenseChargedTo",
    "accountCode",
    "activityDescription",
    "status",
  ],

  conceptNote: [
    "cnNumber",
    "staff_name",
    "staff_role",
    "expense_Charged_To",
    "account_Code",
    "activity_title",
    "activity_location",
    "background_context",
    "objectives_purpose",
    "detailed_activity_description",
    "strategic_plan",
    "benefits_of_project",
    "means_of_verification",
    "status",
  ],

  expenseClaims: [
    "ecNumber",
    "staffName",
    "expenseClaim.from",
    "expenseClaim.to",
    "expenseChargedTo",
    "accountCode",
    "amountInWords",
    "expenseReason",
    "dayOfDeparture",
    "dayOfReturn",
    // "budget",
    "status",
  ],

  paymentRequest: [
    "pmrNumber",
    "requestBy",
    "purposeOfExpense",
    "grantCode",
    "accountNumber",
    "accountName",
    "bankName",
    "specialInstruction",
    "amountInWords",
    "status",
  ],

  purchaseRequest: [
    "pcrNumber",
    "department",
    "suggestedSupplier",
    "requestedBy",
    "address",
    "finalDeliveryPoint",
    "city",
    "expenseChargedTo",
    "accountCode",
    "activityDescription",
    "status",
  ],

  travelRequest: [
    "trNumber",
    "staffName",
    "travelRequest.from",
    "travelRequest.to",
    "expenseChargedTo",
    "accountCode",
    "travelReason",
    "dayOfDeparture",
    "dayOfReturn",
    // "budget",
    "amountInWords",
    "status",
  ],
};

module.exports = searchConfig;
